# Generated by Django 3.2.3 on 2021-10-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='publication',
        ),
    ]
