# Generated by Django 3.2.3 on 2021-11-09 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0012_remove_product_influencer'),
        ('layout', '0009_image_thumbnail'),
        ('capsule', '0002_auto_20211021_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='slug',
        ),
        migrations.AddField(
            model_name='influencer',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencer', to='taleoftiles.publication'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencer', to='layout.image'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='long_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='influencer',
            name='palette1',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='influencer',
            name='palette2',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='influencer',
            name='palette3',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='influencer',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencer', to='taleoftiles.tag'),
        ),
    ]
