# Generated by Django 3.0.2 on 2020-02-26 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='', max_length=100, unique=True)),
                ('completion_status', models.CharField(choices=[('e', 'Empty'), ('s', 'Started'), ('c', 'Completed'), ('o', 'Ordered'), ('ex', 'Expired')], default='e', max_length=2)),
                ('order_status', models.CharField(choices=[('w', 'In Wait'), ('i', 'Received'), ('p', 'In Preparazione'), ('s', 'Spedito'), ('l', 'Lost'), ('r', 'Ricevuto'), ('c', 'Confermato')], default='w', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_val', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('char_val', models.CharField(blank=True, default=1, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('tag', models.CharField(default='-', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('samplable', models.BooleanField(default=True)),
                ('wait_time', models.PositiveIntegerField(default=15)),
                ('min_ammount', models.PositiveIntegerField(default=5)),
                ('source', models.CharField(default='Italy', max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='taleoftiles.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sampler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='', max_length=100, unique=True)),
                ('completion_status', models.CharField(choices=[('e', 'Empty'), ('s', 'Started'), ('c', 'Completed'), ('o', 'Ordered'), ('ex', 'Expired')], default='e', max_length=2)),
                ('order_status', models.CharField(choices=[('w', 'In Wait'), ('i', 'Received'), ('p', 'In Preparazione'), ('s', 'Spedito'), ('l', 'Lost'), ('r', 'Ricevuto'), ('c', 'Confermato')], default='w', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.CharField(default=1, max_length=200, unique=True)),
                ('public', models.BooleanField(default=True)),
                ('in_menu', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_status', models.CharField(choices=[('e', 'Empty'), ('s', 'Started'), ('c', 'Completed'), ('o', 'Ordered'), ('ex', 'Expired')], default='e', max_length=2)),
                ('name', models.CharField(default='', max_length=100)),
                ('surname', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('telephone', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('address2', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('postcode', models.CharField(default='', max_length=100)),
                ('note', models.TextField(max_length=200, null=True)),
                ('internal_tracking_id', models.CharField(default='', max_length=100)),
                ('external_tracking_id', models.CharField(default='', max_length=100)),
                ('chart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart', to='taleoftiles.Chart', verbose_name='Chart')),
                ('sampler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='taleoftiles.Sampler', verbose_name='Sampler')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(blank=True, null=True, related_name='settings', to='taleoftiles.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample', to='taleoftiles.Product', verbose_name='Products')),
                ('sampler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample', to='taleoftiles.Sampler', verbose_name='Sampler')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('collection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='taleoftiles.Collection')),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='taleoftiles.Post')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='taleoftiles.Product')),
                ('setting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='taleoftiles.Setting')),
                ('tag', models.ManyToManyField(default=1, related_name='publication', to='taleoftiles.Tag', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('imagefile', models.ImageField(blank=True, help_text='Load an image.', null=True, upload_to='photos')),
                ('order', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='taleoftiles.Collection')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='taleoftiles.Product')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='taleoftiles.Setting')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.BooleanField(default=False)),
                ('squared_meter', models.PositiveIntegerField(default=1)),
                ('chart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_item', to='taleoftiles.Chart', verbose_name='Charts')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_item', to='taleoftiles.Product', verbose_name='Products')),
            ],
        ),
    ]
