# Generated by Django 3.0.2 on 2020-04-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('public', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='taleoftiles.Tag')),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('tag', models.ManyToManyField(blank=True, related_name='publication', to='taleoftiles.Tag', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('samplable', models.BooleanField(default=True, null=True)),
                ('wait_time', models.PositiveIntegerField(default=15)),
                ('min_ammount', models.PositiveIntegerField(default=5)),
                ('source', models.CharField(default='Italy', max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='taleoftiles.Publication')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='taleoftiles.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('imagefile', models.ImageField(blank=True, help_text='Load an image.', null=True, upload_to='photos')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='taleoftiles.Product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
