# Generated by Django 3.0.2 on 2020-10-25 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('file', models.FileField(upload_to='techspecs/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_it', models.CharField(max_length=200, null=True)),
                ('name_sv', models.CharField(max_length=200, null=True)),
                ('name_de', models.CharField(max_length=200, null=True)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('summary_en', models.CharField(blank=True, max_length=200, null=True)),
                ('summary_it', models.CharField(blank=True, max_length=200, null=True)),
                ('summary_sv', models.CharField(blank=True, max_length=200, null=True)),
                ('summary_de', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('public', models.BooleanField(default=True)),
                ('in_catalogue', models.BooleanField(default=False)),
                ('in_menu', models.BooleanField(default=False)),
                ('in_home', models.BooleanField(default=False)),
                ('in_product_edit', models.BooleanField(default=False)),
                ('in_footer', models.BooleanField(default=False)),
                ('data_type', models.CharField(choices=[('t', 'Text'), ('b', 'Boolean'), ('c', 'Color'), ('i', 'Integer')], default='t', max_length=2)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='taleoftiles.Tag')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('title_en', models.CharField(max_length=200, null=True, unique=True)),
                ('title_it', models.CharField(max_length=200, null=True, unique=True)),
                ('title_sv', models.CharField(max_length=200, null=True, unique=True)),
                ('title_de', models.CharField(max_length=200, null=True, unique=True)),
                ('content', models.TextField()),
                ('content_en', models.TextField(null=True)),
                ('content_it', models.TextField(null=True)),
                ('content_sv', models.TextField(null=True)),
                ('content_de', models.TextField(null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('publish_date', models.DateTimeField(blank=True, verbose_name='date published')),
                ('slug', models.CharField(blank=True, max_length=200, unique=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wait_time', models.PositiveIntegerField(default=15)),
                ('min_ammount', models.PositiveIntegerField(default=5)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('is_decor', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='taleoftiles.Publication')),
                ('support_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supports', to='taleoftiles.Product')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='taleoftiles.Tag')),
                ('techspec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='taleoftiles.TechnicalSpec')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euros', models.FloatField(default=10)),
                ('m2_box', models.FloatField(default=10)),
                ('weight_box', models.FloatField(default=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='taleoftiles.Product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='taleoftiles.Tag')),
            ],
        ),
    ]
