# Generated by Django 3.0.2 on 2020-01-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='summary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
