# Generated by Django 3.0.2 on 2020-02-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='slug',
            field=models.CharField(default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finish',
            name='slug',
            field=models.CharField(default=' ', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='format',
            name='slug',
            field=models.CharField(default=' ', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
