# Generated by Django 3.0.2 on 2020-11-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='content_sv',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='title_sv',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_sv',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='summary_de',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='summary_sv',
        ),
    ]
