# Generated by Django 3.0.2 on 2020-05-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
