# Generated by Django 3.0.2 on 2020-05-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='in_home',
            field=models.BooleanField(default=False),
        ),
    ]
