# Generated by Django 3.0.2 on 2020-02-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='publication', to='taleoftiles.Tag', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
