# Generated by Django 3.0.2 on 2020-02-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0002_auto_20200226_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='internal_name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
