# Generated by Django 3.0.2 on 2020-02-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0002_auto_20200228_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='title',
            field=models.CharField(default='white', max_length=100),
        ),
        migrations.AddField(
            model_name='finish',
            name='title',
            field=models.CharField(default='matte', max_length=100),
        ),
        migrations.AddField(
            model_name='format',
            name='title',
            field=models.CharField(default='10x10', max_length=100),
        ),
        migrations.AlterField(
            model_name='color',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finish',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='format',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
