# Generated by Django 3.0.2 on 2020-11-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0002_auto_20201102_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
