# Generated by Django 3.0.2 on 2020-05-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0002_tag_in_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
    ]
