# Generated by Django 3.0.2 on 2020-11-14 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0003_product_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Products'},
        ),
    ]
