# Generated by Django 3.0.2 on 2020-02-12 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0003_auto_20200205_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='sampler',
            name='completion_status',
            field=models.CharField(choices=[('s', 'Started'), ('c', 'Completed'), ('o', 'Ordered'), ('e', 'Expired')], default='s', max_length=2),
        ),
        migrations.AddField(
            model_name='sampler',
            name='order_status',
            field=models.CharField(choices=[('w', 'In Wait'), ('i', 'Received'), ('p', 'In Preparazione'), ('s', 'Spedito'), ('l', 'Lost'), ('r', 'Ricevuto'), ('c', 'Confermato')], default='w', max_length=2),
        ),
        migrations.AddField(
            model_name='sampler',
            name='session_id',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='completion_status',
            field=models.CharField(choices=[('s', 'Started'), ('c', 'Completed'), ('o', 'Ordered'), ('e', 'Expired')], default='s', max_length=2),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taleoftiles.Product', verbose_name='Products')),
                ('sampler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taleoftiles.Sampler', verbose_name='Sampler')),
            ],
        ),
    ]
