# Generated by Django 3.0.2 on 2020-03-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0004_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_decor',
            field=models.BooleanField(default=False),
        ),
    ]
