# Generated by Django 3.0.2 on 2020-11-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0004_auto_20201114_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='catalogues', to='taleoftiles.Product'),
        ),
    ]
