# Generated by Django 3.0.2 on 2020-05-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0004_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='in_product_edit',
            field=models.BooleanField(default=False),
        ),
    ]
