# Generated by Django 3.0.2 on 2020-02-12 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0004_auto_20200212_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='sample',
        ),
        migrations.AddField(
            model_name='sample',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample', to='taleoftiles.Product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sampler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample', to='taleoftiles.Sampler', verbose_name='Sampler'),
        ),
    ]
