# Generated by Django 3.0.2 on 2020-11-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0005_catalogue_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='MPN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
