# Generated by Django 3.0.2 on 2020-03-01 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0005_product_is_decor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnicalSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='single_sell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='specs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection', to='taleoftiles.TecnicalSpec'),
        ),
    ]
