# Generated by Django 3.0.2 on 2020-02-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0006_auto_20200213_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='num_img_sampler',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
