# Generated by Django 3.0.2 on 2020-03-03 11:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0006_auto_20200301_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='question',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='taleoftiles.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='telephone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
