# Generated by Django 3.0.2 on 2020-05-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0006_auto_20200512_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='formats',
            new_name='size',
        ),
    ]
