# Generated by Django 3.0.2 on 2020-11-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0006_product_mpn'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasyProductProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taleoftiles.product',),
        ),
    ]
