# Generated by Django 3.0.2 on 2020-03-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0007_auto_20200303_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='formats',
        ),
        migrations.AddField(
            model_name='collection',
            name='formats',
            field=models.ManyToManyField(blank=True, related_name='collection', to='taleoftiles.Format'),
        ),
    ]
