# Generated by Django 3.0.2 on 2020-02-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0007_setting_num_img_sampler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_val', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('char_val', models.CharField(blank=True, default=1, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('tag', models.CharField(default='-', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='setting',
            name='num_img_sampler',
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
