# Generated by Django 3.0.2 on 2020-11-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0007_easyproductproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
