# Generated by Django 3.0.2 on 2020-02-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0008_auto_20200214_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampler',
            name='completion_status',
            field=models.CharField(choices=[('e', 'Empty'), ('s', 'Started'), ('c', 'Completed'), ('o', 'Ordered'), ('ex', 'Expired')], default='e', max_length=2),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='completion_status',
            field=models.CharField(choices=[('e', 'Empty'), ('s', 'Started'), ('c', 'Completed'), ('o', 'Ordered'), ('ex', 'Expired')], default='e', max_length=2),
        ),
    ]
