# Generated by Django 3.0.2 on 2020-03-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0008_auto_20200303_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartitem',
            old_name='squared_meter',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='chartitem',
            name='format_chosen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_item', to='taleoftiles.Format', verbose_name='Formats'),
        ),
    ]
