# Generated by Django 3.1.3 on 2020-12-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0008_price_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='summary_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
