# Generated by Django 3.1.3 on 2021-01-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0009_auto_20201218_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='catalogues', to='taleoftiles.Product'),
        ),
    ]
