# Generated by Django 3.0.2 on 2020-02-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0009_auto_20200214_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='user',
        ),
        migrations.AddField(
            model_name='shipping',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shipping',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shipping',
            name='external_tracking_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shipping',
            name='internal_tracking_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shipping',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shipping',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shipping',
            name='telephone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
