# Generated by Django 3.0.2 on 2020-05-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0009_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='content_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='content_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_de',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_en',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_it',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_sv',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
