# Generated by Django 3.0.2 on 2020-06-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0010_auto_20200526_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='technicalspec',
            name='icons',
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
