# Generated by Django 3.0.2 on 2020-02-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0010_auto_20200214_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampler',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sampler', to='taleoftiles.Shipping', verbose_name='Shippings'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='address2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shipping',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shipping',
            name='note',
            field=models.TextField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='postcode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
