# Generated by Django 3.2.3 on 2021-10-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0002_auto_20211021_1025'),
        ('taleoftiles', '0010_auto_20210107_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='capsule.influencer'),
        ),
    ]
