# Generated by Django 3.2.3 on 2021-11-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0011_product_influencer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='influencer',
        ),
    ]
