# Generated by Django 3.0.2 on 2020-02-18 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0011_auto_20200218_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampler',
            name='product',
        ),
        migrations.AddField(
            model_name='shipping',
            name='sampler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping', to='taleoftiles.Sampler', verbose_name='Sampler'),
        ),
    ]
