# Generated by Django 3.0.2 on 2020-07-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0011_auto_20200604_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='m2_box',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='price',
            name='weight_box',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
