# Generated by Django 3.0.2 on 2020-02-18 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0012_auto_20200218_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='sampler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='taleoftiles.Sampler', verbose_name='Sampler'),
            preserve_default=False,
        ),
    ]
