# Generated by Django 3.0.2 on 2020-07-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0012_auto_20200722_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='euros',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='m2_box',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='weight_box',
            field=models.FloatField(default=10),
        ),
    ]
