# Generated by Django 3.0.2 on 2020-09-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0013_auto_20200722_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Tags'},
        ),
    ]
