# Generated by Django 3.0.2 on 2020-02-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0013_auto_20200218_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='note',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
