# Generated by Django 3.0.2 on 2020-02-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0014_auto_20200219_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='setting',
        ),
        migrations.AddField(
            model_name='product',
            name='setting',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='taleoftiles.Setting'),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='tag',
        ),
        migrations.AddField(
            model_name='publication',
            name='tag',
            field=models.ManyToManyField(default=1, related_name='publication', to='taleoftiles.Tag', verbose_name='Category'),
        ),
    ]
