# Generated by Django 3.0.2 on 2020-10-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0014_auto_20200929_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='in_footer',
            field=models.BooleanField(default=False),
        ),
    ]
