# Generated by Django 3.0.2 on 2020-02-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0015_auto_20200219_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='setting',
        ),
        migrations.AddField(
            model_name='setting',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='settings', to='taleoftiles.Product'),
        ),
    ]
