# Generated by Django 3.0.2 on 2020-10-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0015_tag_in_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_samplable',
        ),
    ]
