# Generated by Django 3.0.2 on 2020-02-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0016_auto_20200220_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='product',
            new_name='products',
        ),
    ]
