# Generated by Django 3.0.2 on 2020-02-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0017_auto_20200220_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wait_time',
            field=models.TimeField(null=True),
        ),
    ]
