# Generated by Django 3.0.2 on 2020-02-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0018_product_wait_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_ammount',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='wait_time',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
