# Generated by Django 3.0.2 on 2020-02-21 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0019_auto_20200220_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='completion_status',
            field=models.CharField(choices=[('e', 'Empty'), ('s', 'Started'), ('c', 'Completed'), ('o', 'Ordered'), ('ex', 'Expired')], default='e', max_length=2),
        ),
        migrations.AddField(
            model_name='chart',
            name='order_status',
            field=models.CharField(choices=[('w', 'In Wait'), ('i', 'Received'), ('p', 'In Preparazione'), ('s', 'Spedito'), ('l', 'Lost'), ('r', 'Ricevuto'), ('c', 'Confermato')], default='w', max_length=2),
        ),
        migrations.AddField(
            model_name='chart',
            name='session_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sampler',
            name='session_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ChartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.BooleanField(default=False)),
                ('chart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_item', to='taleoftiles.Chart', verbose_name='Charts')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_item', to='taleoftiles.Product', verbose_name='Products')),
            ],
        ),
    ]
