# Generated by Django 3.0.2 on 2020-02-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0020_auto_20200221_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartitem',
            name='squared_meter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
