# Generated by Django 3.0.2 on 2020-02-21 10:47

from django.db import migrations, models
import taleoftiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0021_chartitem_squared_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartitem',
            name='squared_meter',
            field=models.PositiveIntegerField(default=0, validators=[taleoftiles.models.min_ammount]),
        ),
    ]
