# Generated by Django 3.0.2 on 2020-02-21 10:52

from django.db import migrations, models
import taleoftiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0022_auto_20200221_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartitem',
            name='squared_meter',
            field=models.PositiveIntegerField(default=1, validators=[taleoftiles.models.min_ammount]),
        ),
    ]
