# Generated by Django 3.0.2 on 2020-02-23 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0023_auto_20200221_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='taleoftiles.Post'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='chart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart', to='taleoftiles.Chart', verbose_name='Chart'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='sampler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='taleoftiles.Sampler', verbose_name='Sampler'),
        ),
    ]
