# Generated by Django 3.0.2 on 2020-06-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
