# Generated by Django 3.0.2 on 2020-06-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0011_auto_20200604_1009'),
        ('blog', '0002_post_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='posts', to='taleoftiles.Product'),
        ),
    ]
