# Generated by Django 3.0.2 on 2020-05-04 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taleoftiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='', max_length=100)),
                ('completion_status', models.CharField(choices=[('s', 'Started'), ('c', 'Completed'), ('o', 'Ordered'), ('ex', 'Expired'), ('cs', 'Closed by Staff')], default='s', max_length=2)),
                ('order_status', models.CharField(choices=[('w', 'In Wait'), ('i', 'Received'), ('p', 'In Preparazione'), ('s', 'Spedito'), ('l', 'Lost'), ('r', 'Ricevuto'), ('c', 'Confermato')], default='w', max_length=2)),
                ('is_sample', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('modified_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(editable=False, verbose_name='date created')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='CRM.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=200, null=True)),
                ('internal_tracking_id', models.CharField(default='', max_length=100)),
                ('shipping_tracking_id', models.CharField(default='', max_length=100)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='CRM.Chart', verbose_name='Chart')),
            ],
        ),
        migrations.CreateModel(
            name='ChartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'ok'), ('ns', 'Not Samplable'), ('le', 'Limit Exceeded'), ('ru', 'Removed by User'), ('rs', 'Removed by Staff'), ('o', 'Others')], default='ok', max_length=2)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField()),
                ('chart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_item', to='CRM.Chart', verbose_name='Charts')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_item', to='taleoftiles.Product', verbose_name='Products')),
            ],
        ),
    ]
