# Generated by Django 3.0.2 on 2020-10-25 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taleoftiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='', max_length=100, null=True)),
                ('completion_status', models.CharField(choices=[('s', 'Started'), ('c', 'Completed'), ('p', 'Payed'), ('ex', 'Expired'), ('cs', 'Closed by Staff')], default='s', max_length=2)),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('internal_tracking_id', models.CharField(default='', max_length=100)),
                ('shipping_tracking_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField()),
                ('order_status', models.CharField(choices=[('w', 'In Wait'), ('i', 'Received'), ('p', 'In Preparazione'), ('s', 'Spedito'), ('l', 'Lost'), ('r', 'Ricevuto'), ('c', 'Confermato')], default='w', max_length=2)),
                ('final_payment', models.PositiveIntegerField(default=0)),
                ('is_sampler', models.BooleanField(default=False)),
                ('shipping_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=100)),
                ('fullname', models.TextField(max_length=100)),
                ('country', models.CharField(choices=[('it', 'Italia'), ('sv', 'Sverige'), ('dk', 'Danmark'), ('at', 'Österreich'), ('fr', 'France'), ('de', 'Deutscheland'), ('be', 'Belgique'), ('nl', 'Nederland'), ('lu', 'Lëtzebuerg')], default='it', max_length=2)),
                ('city', models.TextField(max_length=100)),
                ('CAP', models.TextField(max_length=10)),
                ('shipping_address', models.TextField(max_length=100)),
                ('telephone_num', models.TextField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRM.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Sampler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='', max_length=100, null=True)),
                ('completion_status', models.CharField(choices=[('s', 'Started'), ('c', 'Completed'), ('p', 'Payed'), ('ex', 'Expired'), ('cs', 'Closed by Staff')], default='s', max_length=2)),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sampler', to='CRM.Order', verbose_name='Order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samplers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'ok'), ('ns', 'Not Samplable'), ('le', 'Limit Exceeded'), ('ru', 'Removed by User'), ('rs', 'Removed by Staff'), ('o', 'Others')], default='ok', max_length=2)),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='taleoftiles.Product', verbose_name='Products')),
                ('sampler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='CRM.Sampler', verbose_name='Samples')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('modified_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(editable=False, verbose_name='date created')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('public', models.BooleanField(default=False)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='CRM.Question')),
            ],
        ),
        migrations.CreateModel(
            name='ChartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('has_frido', models.BooleanField(default=True)),
                ('boxes', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('status', models.CharField(choices=[('ok', 'ok'), ('ns', 'Not Samplable'), ('le', 'Limit Exceeded'), ('ru', 'Removed by User'), ('rs', 'Removed by Staff'), ('o', 'Others')], default='ok', max_length=2)),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField()),
                ('chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_item', to='CRM.Chart', verbose_name='Charts')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_item', to='taleoftiles.Product', verbose_name='Products')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_item', to='taleoftiles.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='chart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charts', to='CRM.Order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='chart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charts', to=settings.AUTH_USER_MODEL),
        ),
    ]
