# Generated by Django 3.0.2 on 2020-04-21 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taleoftiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='', max_length=100, unique=True)),
                ('completion_status', models.CharField(choices=[('e', 'Empty'), ('s', 'Started'), ('c', 'Completed'), ('o', 'Ordered'), ('ex', 'Expired')], default='e', max_length=2)),
                ('order_status', models.CharField(choices=[('w', 'In Wait'), ('i', 'Received'), ('p', 'In Preparazione'), ('s', 'Spedito'), ('l', 'Lost'), ('r', 'Ricevuto'), ('c', 'Confermato')], default='w', max_length=2)),
                ('is_sample', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('chart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_item', to='CRM.Chart', verbose_name='Charts')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_item', to='taleoftiles.Product', verbose_name='Products')),
            ],
        ),
    ]
