# Generated by Django 3.0.2 on 2020-04-21 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='CRM.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=200, null=True)),
                ('internal_tracking_id', models.CharField(default='', max_length=100)),
                ('shipping_tracking_id', models.CharField(default='', max_length=100)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='CRM.Chart', verbose_name='Chart')),
            ],
        ),
    ]
