# Generated by Django 3.0.2 on 2020-05-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='user',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='profile',
        ),
    ]
