# Generated by Django 3.0.2 on 2020-05-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='country',
            field=models.CharField(choices=[('it', 'Italia'), ('sv', 'Svezia')], default='it', max_length=2),
        ),
    ]
