# Generated by Django 3.0.2 on 2020-11-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('w', 'In Wait'), ('i', 'Received'), ('p', 'In Preparation'), ('s', 'Sent'), ('l', 'Lost'), ('r', 'Received'), ('c', 'Confermato')], default='w', max_length=2),
        ),
    ]
