# Generated by Django 3.0.2 on 2020-05-04 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chart',
            name='session_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(blank=True, max_length=100)),
                ('country', models.TextField(blank=True, max_length=100)),
                ('city', models.TextField(blank=True, max_length=100)),
                ('CAP', models.TextField(blank=True, max_length=10)),
                ('shipping_address', models.TextField(blank=True, max_length=100)),
                ('telephone_num', models.TextField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
