# Generated by Django 3.0.2 on 2020-05-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0007_auto_20200512_1434'),
        ('CRM', '0002_auto_20200511_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='chartitem',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_item', to='taleoftiles.Price'),
        ),
    ]
