# Generated by Django 3.0.2 on 2020-05-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_auto_20200504_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='completion_status',
            field=models.CharField(choices=[('s', 'Started'), ('i1', 'In Checkout 1'), ('i2', 'In Checkout 2'), ('i3', 'In Checkout 3'), ('c', 'Completed'), ('o', 'Ordered'), ('ex', 'Expired'), ('cs', 'Closed by Staff')], default='s', max_length=2),
        ),
    ]
