# Generated by Django 3.0.2 on 2020-05-05 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0003_auto_20200505_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='completion_status',
            field=models.CharField(choices=[('s', 'Started'), ('i1', 'In Checkout 1'), ('i2', 'In Checkout 2'), ('c', 'Completed'), ('o', 'Ordered'), ('ex', 'Expired'), ('cs', 'Closed by Staff')], default='s', max_length=2),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
