# Generated by Django 3.1.3 on 2020-12-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_auto_20201104_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(max_length=20)),
                ('number_use', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
