# Generated by Django 3.0.2 on 2020-05-12 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0007_auto_20200512_1434'),
        ('CRM', '0003_auto_20200512_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartitem',
            name='price',
        ),
        migrations.AddField(
            model_name='chartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_item', to='taleoftiles.Product', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='chartitem',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_item', to='taleoftiles.Tag', verbose_name='Tags'),
        ),
    ]
