# Generated by Django 3.1.3 on 2020-12-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='actual_use',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
