# Generated by Django 3.0.2 on 2020-05-13 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0007_auto_20200512_1434'),
        ('CRM', '0004_auto_20200512_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartitem',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_item', to='CRM.Chart', verbose_name='Charts'),
        ),
        migrations.AlterField(
            model_name='chartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_item', to='taleoftiles.Product', verbose_name='Products'),
        ),
    ]
