# Generated by Django 3.0.2 on 2020-05-05 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_auto_20200505_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.Profile'),
        ),
    ]
