# Generated by Django 3.0.2 on 2020-05-05 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_auto_20200505_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='chart',
        ),
        migrations.AddField(
            model_name='chart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='CRM.Order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='completion_status',
            field=models.CharField(choices=[('s', 'Started'), ('i1', 'In Checkout 1'), ('i2', 'In Checkout 2'), ('c', 'Completed'), ('p', 'Payed'), ('ex', 'Expired'), ('cs', 'Closed by Staff')], default='s', max_length=2),
        ),
    ]
