# Generated by Django 3.0.2 on 2020-05-13 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_auto_20200513_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartitem',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_item', to='CRM.Chart', verbose_name='Charts'),
        ),
    ]
