# Generated by Django 3.2.3 on 2021-05-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartitem',
            name='status',
            field=models.CharField(choices=[('ok', 'Ok'), ('ns', 'Not Samplable'), ('le', 'Limit Exceeded'), ('ru', 'Removed by User'), ('rs', 'Removed by Staff'), ('o', 'Others')], default='ok', max_length=2),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('ok', 'Ok'), ('ns', 'Not Samplable'), ('le', 'Limit Exceeded'), ('ru', 'Removed by User'), ('rs', 'Removed by Staff'), ('o', 'Others')], default='ok', max_length=2),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='country',
            field=models.CharField(choices=[('it', 'Italia'), ('at', 'Österreich'), ('fr', 'France'), ('de', 'Deutscheland'), ('be', 'Belgique'), ('nl', 'Nederland'), ('lu', 'Lëtzebuerg')], default='it', max_length=2),
        ),
    ]
