# Generated by Django 3.2.3 on 2021-05-28 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0010_auto_20210107_0931'),
        ('CRM', '0007_auto_20210528_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartitem',
            name='finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_item_f', to='taleoftiles.tag', verbose_name='Finishes'),
        ),
    ]
