# Generated by Django 3.2.3 on 2021-12-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_chartitem_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartitem',
            name='note',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
