# Generated by Django 3.0.2 on 2020-05-14 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0007_auto_20200512_1434'),
        ('CRM', '0009_auto_20200514_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_item', to='taleoftiles.Product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='chartitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_item', to='taleoftiles.Tag', verbose_name='Tags'),
        ),
    ]
