# Generated by Django 3.2.3 on 2021-12-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_chartitem_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartitem',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
