# Generated by Django 3.2.3 on 2021-12-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_alter_chartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartitem',
            name='saved_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
