# Generated by Django 3.0.2 on 2020-05-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_auto_20200514_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartitem',
            name='has_frido',
            field=models.BooleanField(default=True),
        ),
    ]
