# Generated by Django 3.0.2 on 2020-05-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_chartitem_has_frido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='CAP',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='city',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='fullname',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='telephone_num',
            field=models.TextField(max_length=30),
        ),
    ]
