# Generated by Django 3.0.2 on 2020-09-04 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taleoftiles', '0013_auto_20200722_1540'),
        ('CRM', '0012_auto_20200526_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='is_sample',
        ),
        migrations.CreateModel(
            name='Sampler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='', max_length=100, null=True)),
                ('completion_status', models.CharField(choices=[('s', 'Started'), ('i1', 'In Checkout 1'), ('i2', 'In Checkout 2'), ('c', 'Completed'), ('p', 'Payed'), ('ex', 'Expired'), ('cs', 'Closed by Staff')], default='s', max_length=2)),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samplers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'ok'), ('ns', 'Not Samplable'), ('le', 'Limit Exceeded'), ('ru', 'Removed by User'), ('rs', 'Removed by Staff'), ('o', 'Others')], default='ok', max_length=2)),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='taleoftiles.Product', verbose_name='Products')),
                ('sampler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='CRM.Sampler', verbose_name='Samples')),
            ],
        ),
    ]
