# Generated by Django 3.0.2 on 2020-09-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0013_auto_20200904_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampler',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
