# Generated by Django 3.0.2 on 2020-09-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0014_sampler_free_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='email',
            field=models.TextField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
