# Generated by Django 3.0.2 on 2020-09-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0015_shipping_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='final_payment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('w', 'In Wait'), ('i', 'Received'), ('p', 'In Preparazione'), ('s', 'Spedito'), ('l', 'Lost'), ('r', 'Ricevuto'), ('c', 'Confermato')], default='w', max_length=2),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='country',
            field=models.CharField(choices=[('it', 'Italia'), ('sv', 'Sverige')], default='it', max_length=2),
        ),
    ]
