# Generated by Django 3.0.2 on 2020-09-08 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0016_auto_20200907_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampler',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samplers', to='CRM.Order', verbose_name='Order'),
        ),
    ]
