# Generated by Django 3.0.2 on 2020-09-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0017_sampler_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_sampler',
            field=models.BooleanField(default=False),
        ),
    ]
