# Generated by Django 3.0.2 on 2020-09-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0018_order_is_sampler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charts', to='CRM.Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='sampler',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samplers', to='CRM.Order', verbose_name='Order'),
        ),
    ]
