# Generated by Django 3.0.2 on 2020-09-09 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0019_auto_20200908_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampler',
            name='free_shipping',
        ),
        migrations.AlterField(
            model_name='chart',
            name='completion_status',
            field=models.CharField(choices=[('s', 'Started'), ('c', 'Completed'), ('p', 'Payed'), ('ex', 'Expired'), ('cs', 'Closed by Staff')], default='s', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sampler',
            name='completion_status',
            field=models.CharField(choices=[('s', 'Started'), ('c', 'Completed'), ('p', 'Payed'), ('ex', 'Expired'), ('cs', 'Closed by Staff')], default='s', max_length=2),
        ),
        migrations.AlterField(
            model_name='sampler',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sampler', to='CRM.Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRM.Profile'),
        ),
    ]
