# Generated by Django 3.0.2 on 2020-09-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0020_auto_20200909_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='country',
            field=models.CharField(choices=[('it', 'Italia'), ('sv', 'Sverige'), ('dk', 'Danmark'), ('at', 'Österreich'), ('fr', 'France'), ('de', 'Deutscheland'), ('be', 'Belgique'), ('nl', 'Nederland'), ('lu', 'Lëtzebuerg')], default='it', max_length=2),
        ),
    ]
