# Generated by Django 3.0.2 on 2020-09-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0021_auto_20200911_1059'),
    ]

    operations = [

    ]
