# Generated by Django 3.0.2 on 2020-10-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0025_auto_20201005_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartitem',
            name='boxes',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
