# Generated by Django 3.0.2 on 2020-05-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_val', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('char_val', models.CharField(blank=True, default=1, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('tag', models.CharField(default='-', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ElementTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('public', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='layout.ElementTag')),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=200)),
                ('content_en', models.TextField(max_length=200, null=True)),
                ('content_it', models.TextField(max_length=200, null=True)),
                ('content_sv', models.TextField(max_length=200, null=True)),
                ('content_de', models.TextField(max_length=200, null=True)),
                ('imagefile', models.ImageField(blank=True, help_text='Load an image.', null=True, upload_to='img')),
                ('public', models.BooleanField(default=True)),
                ('data_type', models.CharField(choices=[('t', 'Text'), ('i', 'Image')], default='t', max_length=2)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element', to='layout.ElementTag')),
            ],
        ),
    ]
