# Generated by Django 3.0.2 on 2020-04-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_val', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('char_val', models.CharField(blank=True, default=1, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('tag', models.CharField(default='-', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
    ]
