# Generated by Django 3.0.2 on 2020-10-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('taleoftiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_val', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('char_val', models.CharField(blank=True, default=1, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('tag', models.CharField(default='-', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, max_length=200, null=True)),
                ('content_en', models.TextField(blank=True, max_length=200, null=True)),
                ('content_it', models.TextField(blank=True, max_length=200, null=True)),
                ('content_sv', models.TextField(blank=True, max_length=200, null=True)),
                ('content_de', models.TextField(blank=True, max_length=200, null=True)),
                ('public', models.BooleanField(default=True)),
                ('data_type', models.CharField(choices=[('t', 'Text'), ('i', 'Image')], default=('t', 'Text'), max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('tag', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icons', to='taleoftiles.Tag')),
                ('techspecs', models.ManyToManyField(blank=True, related_name='icons', to='taleoftiles.TechnicalSpec')),
            ],
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('subj', models.CharField(max_length=250)),
                ('subj_en', models.CharField(max_length=250, null=True)),
                ('subj_it', models.CharField(max_length=250, null=True)),
                ('subj_sv', models.CharField(max_length=250, null=True)),
                ('subj_de', models.CharField(max_length=250, null=True)),
                ('sender', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('content_en', models.TextField(blank=True, max_length=500, null=True)),
                ('content_it', models.TextField(blank=True, max_length=500, null=True)),
                ('content_sv', models.TextField(blank=True, max_length=500, null=True)),
                ('content_de', models.TextField(blank=True, max_length=500, null=True)),
                ('template_id', models.CharField(max_length=50)),
                ('template_vs', models.CharField(max_length=50)),
                ('no_reply', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('imagefile', models.ImageField(blank=True, help_text='Load an image.', null=True, upload_to='photos')),
                ('thumbnail', models.ImageField(editable=False, null=True, upload_to='thumbs')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('element', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='layout.Element')),
                ('finish_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finish_images', to='taleoftiles.Tag')),
                ('format_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format_images', to='taleoftiles.Tag')),
                ('icon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='layout.Icon')),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover', to='blog.Post')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='taleoftiles.Product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ElementTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('public', models.BooleanField(default=True)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='layout.ElementTag')),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='element',
            name='tag',
            field=models.ManyToManyField(related_name='element', to='layout.ElementTag'),
        ),
    ]
