# Generated by Django 3.0.2 on 2020-11-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='element',
            name='content_sv',
        ),
        migrations.RemoveField(
            model_name='mailtemplate',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='mailtemplate',
            name='content_sv',
        ),
        migrations.RemoveField(
            model_name='mailtemplate',
            name='subj_de',
        ),
        migrations.RemoveField(
            model_name='mailtemplate',
            name='subj_sv',
        ),
    ]
