# Generated by Django 3.1.3 on 2020-12-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_auto_20201102_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
