# Generated by Django 3.0.2 on 2020-04-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_elementtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='layout.ElementTag'),
        ),
    ]
