# Generated by Django 3.0.2 on 2020-05-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_auto_20200506_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='tag',
        ),
        migrations.AddField(
            model_name='element',
            name='tag',
            field=models.ManyToManyField(related_name='element', to='layout.ElementTag'),
        ),
    ]
