# Generated by Django 3.1.3 on 2020-12-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_translationfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationfile',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='translationfile',
            name='content_it',
            field=models.TextField(null=True),
        ),
    ]
