# Generated by Django 3.0.2 on 2020-05-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_auto_20200506_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('subj', models.CharField(max_length=250)),
                ('subj_en', models.CharField(max_length=250, null=True)),
                ('subj_it', models.CharField(max_length=250, null=True)),
                ('subj_sv', models.CharField(max_length=250, null=True)),
                ('subj_de', models.CharField(max_length=250, null=True)),
                ('sender', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('content_en', models.TextField(blank=True, max_length=500, null=True)),
                ('content_it', models.TextField(blank=True, max_length=500, null=True)),
                ('content_sv', models.TextField(blank=True, max_length=500, null=True)),
                ('content_de', models.TextField(blank=True, max_length=500, null=True)),
                ('template_name', models.CharField(max_length=50)),
                ('template_vs', models.CharField(max_length=50)),
                ('no_reply', models.BooleanField(default=False)),
            ],
        ),
    ]
