# Generated by Django 3.0.2 on 2020-04-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_element_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementtag',
            name='name_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='elementtag',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='elementtag',
            name='name_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='elementtag',
            name='name_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='elementtag',
            name='summary_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='elementtag',
            name='summary_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='elementtag',
            name='summary_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='elementtag',
            name='summary_sv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
