# Generated by Django 3.0.2 on 2020-05-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0004_mailtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailtemplate',
            old_name='template_name',
            new_name='template_id',
        ),
    ]
