# Generated by Django 3.1.3 on 2020-12-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0004_auto_20201205_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationfile',
            name='version',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
