# Generated by Django 3.1.3 on 2020-12-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0005_translationfile_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='content_fr',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='content_fr',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='subj_fr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='translationfile',
            name='content_fr',
            field=models.TextField(null=True),
        ),
    ]
