# Generated by Django 3.0.2 on 2020-06-04 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0006_auto_20200604_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='element',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='layout.Element'),
        ),
    ]
