# Generated by Django 3.2.3 on 2021-06-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0006_auto_20201218_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Load an image.', null=True, upload_to='thumbs'),
        ),
    ]
