# Generated by Django 3.1.3 on 2021-01-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0006_auto_20201218_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
    ]
