# Generated by Django 3.2.3 on 2021-06-17 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0007_alter_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
    ]
