# Generated by Django 3.0.2 on 2020-06-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('layout', '0007_auto_20200604_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='blog.Post'),
        ),
    ]
