# Generated by Django 3.0.2 on 2020-07-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleoftiles', '0011_auto_20200604_1009'),
        ('layout', '0009_auto_20200616_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='finish_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finish_images', to='taleoftiles.Tag'),
        ),
        migrations.AddField(
            model_name='image',
            name='format_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format_images', to='taleoftiles.Tag'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='thumbs'),
        ),
    ]
