# Generated by Django 3.0.2 on 2020-09-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0010_auto_20200722_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-order']},
        ),
    ]
