# Generated by Django 3.0.2 on 2020-10-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0011_auto_20200929_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
    ]
